# Generated by Django 4.2.30 on 2026-04-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_city_user_country_user_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
