# Generated by Django 4.2.30 on 2026-04-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_file',
        ),
        migrations.AddField(
            model_name='lesson',
            name='bunny_video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
