# Generated by Django 4.2.30 on 2026-04-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_lesson_video_file_lesson_bunny_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='notes_file',
        ),
        migrations.AddField(
            model_name='lesson',
            name='notes_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
