# Generated by Django 4.2.30 on 2026-04-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_lesson_notes_file_lesson_notes_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
